/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui;

import br.newtonpaiva.gc.ui.utils.TelaPesquisa;
import static br.newtonpaiva.util.Mensagens.*;
import br.newtowpaiva.modelo.Convenio;
import br.newtowpaiva.modelo.ConvenioSituacao;
import br.newtowpaiva.modelo.Curso;
import br.newtowpaiva.modelo.Empresa;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoConvenioSituacaoNuloException;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoCursoNuloException;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoDataAssinaturaErradoException;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoDataAssinaturaNuloException;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoDataVencimentoErradoException;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoDataVencimentoNuloException;
import br.newtowpaiva.modelo.execoes.ConvenioInvalidoException;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class TelaConvenios extends javax.swing.JDialog {

    private Convenio convenioSelecionado;
    private Empresa empresaSelecionada;

    /**
     * Creates new form TelaConvenios
     *
     * @param parent
     * @param modal
     */
    public TelaConvenios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
        * posiciona a tela no centro da tela
         */
        setLocationRelativeTo(parent);
        /*
        * ao usuário clicar enter ele aciona o botão Salvar
         */
        getRootPane().setDefaultButton(btnSalvar);

        CursosComponente();
        SituacaoComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEmpresa = new javax.swing.JPanel();
        lblCnpj = new javax.swing.JLabel();
        jspCnpj = new javax.swing.JFormattedTextField();
        btnPesquisaEmpresa = new javax.swing.JButton();
        lblNomeEmpresa = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        cbbCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        cbbSituacaoConvenio = new javax.swing.JComboBox<>();
        lblSituacaoConvenio = new javax.swing.JLabel();
        edtVencimento = new javax.swing.JFormattedTextField();
        lblDataEntrada = new javax.swing.JLabel();
        edtAssinatura = new javax.swing.JFormattedTextField();
        lblInicioAtual = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo convênio");
        setResizable(false);

        panEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da empresa"));

        lblCnpj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCnpj.setText("CNPJ");

        try {
            jspCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jspCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jspCnpjFocusLot(evt);
            }
        });

        btnPesquisaEmpresa.setText("...");
        btnPesquisaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEmpresaLayout = new javax.swing.GroupLayout(panEmpresa);
        panEmpresa.setLayout(panEmpresaLayout);
        panEmpresaLayout.setHorizontalGroup(
            panEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpresaLayout.createSequentialGroup()
                .addGroup(panEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEmpresaLayout.createSequentialGroup()
                        .addComponent(lblCnpj)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panEmpresaLayout.createSequentialGroup()
                        .addComponent(jspCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panEmpresaLayout.setVerticalGroup(
            panEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCnpj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jspCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisaEmpresa))
                    .addComponent(lblNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        cbbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona um..." }));

        lblCurso.setText("Curso");

        cbbSituacaoConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona um..." }));

        lblSituacaoConvenio.setText("Situação do convênio");

        try {
            edtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDataEntrada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataEntrada.setText("Data de vencimento");

        try {
            edtAssinatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblInicioAtual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblInicioAtual.setText("Data de assinatura");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCurso)
                                    .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInicioAtual)
                                    .addComponent(edtAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSituacaoConvenio)
                                    .addComponent(cbbSituacaoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataEntrada)
                                    .addComponent(edtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpar)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imgLogo)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInicioAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSituacaoConvenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbSituacaoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDataEntrada)
                        .addGap(8, 8, 8)
                        .addComponent(edtVencimento)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jspCnpjFocusLot(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jspCnpjFocusLot
        //Busca por empresa

    }//GEN-LAST:event_jspCnpjFocusLot

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String Inserir = "N";
        //Se o Convenio edição é nulo
        if (convenioSelecionado == null) {
            //Inicia uma nova classe
            convenioSelecionado = new Convenio();
            Inserir = "S";
        }

        //Inicia uma nova classe de curso
        Curso c = new Curso();
        try {
            if (cbbCurso.getSelectedIndex() > 0) {
                List<Curso> lista = Curso.buscarPorNome((String) cbbCurso.getSelectedItem());
                if (lista.size() < 1) {
                    JOptionPane.showMessageDialog(null, CURSO_NAO_EXISTE);
                    return;
                }
                lista.forEach(Cursos -> {
                    c.setId(Cursos.getId());
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }

        //Inicia uma nova classe de curso
        ConvenioSituacao sc = new ConvenioSituacao();
        try {
            if (cbbCurso.getSelectedIndex() > 0) {
                List<ConvenioSituacao> lista = ConvenioSituacao.buscarPorNome((String) cbbSituacaoConvenio.getSelectedItem());
                if (lista.size() < 1) {
                    JOptionPane.showMessageDialog(null, CURSO_NAO_EXISTE);
                    return;
                }
                lista.forEach(SituacoesConvenios -> {
                    sc.setId(SituacoesConvenios.getId());
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }

        SimpleDateFormat format = new SimpleDateFormat(GERAL_FORMATO_DATA);
        Calendar dataVencimento = Calendar.getInstance();
        try {
            dataVencimento.setTime(format.parse(edtVencimento.getText()));
        } catch (ParseException e) {
            edtVencimento.getText();
            JOptionPane.showMessageDialog(this, CONVENIO_DATA_VENCIMENTO + "\n" + DATA_FORMATACAO);
            return;
        }

        Calendar dataAssintaura = Calendar.getInstance();
        try {
            dataAssintaura.setTime(format.parse(edtAssinatura.getText()));
        } catch (ParseException e) {
            edtAssinatura.getText();
            JOptionPane.showMessageDialog(this, CONVENIO_DATA_ASSINATURA + "\n" + DATA_FORMATACAO);
            return;
        }

        Empresa e = new Empresa();
        String cnpj = jspCnpj.getText();
        if (!cnpj.equals("  .   .   /    -  ")) {
            try {
                e.setId(Empresa.buscarPorCnpj(cnpj).getId());
            } catch (SQLException ex) {
                Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
            }
        }

        //Seta o nome do aluno para salvar (Inserir ou editar)
        convenioSelecionado.setConvenioSituacao(sc);
        convenioSelecionado.setCurso(c);
        convenioSelecionado.setDataAssinatura(dataAssintaura);
        convenioSelecionado.setDataVencimento(dataVencimento);
        convenioSelecionado.setEmpresa(e);
        try {
            //Salvar
            convenioSelecionado.salvar();
            //Mensagem de acordo com a açãso (Edição ou inserção)
            if (Inserir.equals(GERAL_S)) {
                JOptionPane.showMessageDialog(null, CONVENIO_INSERIR_OK);
                Limpar();
                convenioSelecionado = null;
            } else {
                JOptionPane.showMessageDialog(null, CONVENIO_ALTERAR_OK);
            }

        } catch (ConvenioInvalidoException ex) {
            cbbCurso.requestFocus();
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, CONVENIOS_DOIS_ANOS);
        } catch (ConvenioInvalidoDataVencimentoErradoException ex) {
            edtVencimento.requestFocus();
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, DATA_FORMATACAO);
        } catch (ConvenioInvalidoDataAssinaturaErradoException ex) {
            edtAssinatura.requestFocus();
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, DATA_FORMATACAO);
        } catch (ConvenioInvalidoCursoNuloException ex) {
            cbbCurso.requestFocus();
            Logger.getLogger(TelaConvenios.class.getName()).log(Level.SEVERE, null, ex);
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ConvenioInvalidoConvenioSituacaoNuloException ex) {
            cbbSituacaoConvenio.requestFocus();
            Logger.getLogger(TelaConvenios.class.getName()).log(Level.SEVERE, null, ex);
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ConvenioInvalidoDataAssinaturaNuloException ex) {
            edtAssinatura.requestFocus();
            Logger.getLogger(TelaConvenios.class.getName()).log(Level.SEVERE, null, ex);
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ConvenioInvalidoDataVencimentoNuloException ex) {
            edtVencimento.requestFocus();
            Logger.getLogger(TelaConvenios.class.getName()).log(Level.SEVERE, null, ex);
            Logger.getLogger(TelaAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaConvenios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        /*
        * Limpa os componentes
         */
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaEmpresaActionPerformed
        TelaPesquisa tela = new TelaPesquisa(
                null, true);

        tela.setTitle(CONTRATOS_PESQUISAR_EMPRESA);

        tela.getCbbTipoFiltro().removeAllItems();
        tela.getCbbTipoFiltro().addItem(GERAL_RAZAO);
        tela.getCbbTipoFiltro().addItem(GERAL_CNPJ);

        tela.getTableModel().addColumn(GERAL_ID);
        tela.getTableModel().addColumn(GERAL_RAZAO);
        tela.getTableModel().addColumn(GERAL_CNPJ);
        tela.getBtnConsultar().addActionListener((ActionEvent evento) -> {
            try {
                //TelaPesquisa tela1 = (TelaPesquisa) ((JButton) e.getSource()).getParent();

                switch (tela.getCbbTipoFiltro().getSelectedIndex()) {
                    case 0:
                        // Obtem o valor informado na tela
                        String razaoSocial = tela.getEdtFiltro().getText();

                        // Consulta a empresa pelo nome
                        List<Empresa> lista = Empresa.buscarPorNome(razaoSocial);

                        // Limpa a tabela
                        tela.getTableModel().setRowCount(0);

                        if (lista.isEmpty()) {
                            JOptionPane.showMessageDialog(this, EMPRESA_NAO_ENCONTRADA);
                            tela.getEdtFiltro().requestFocus();
                        } else {
                            lista.forEach(emp -> {
                                Object[] row = {emp.getId(), emp.getCnpjFormatado(), emp.getNome()};
                                tela.getTableModel().addRow(row);
                            });
                        }
                        break;
                    case 1:
                        // Obtem o valor informado na tela
                        String cnpj = tela.getEdtFiltro().getText();

                        // Consulta a empresa pelo CNPJ
                        Empresa emp = Empresa.buscarPorCnpj(cnpj);

                        // Limpa a tabela
                        tela.getTableModel().setRowCount(0);

                        if (emp == null) {
                            JOptionPane.showMessageDialog(this, EMPRESA_NAO_ENCONTRADA);
                            tela.getEdtFiltro().requestFocus();
                        } else {
                            Object[] row = {emp.getId(), emp.getCnpjFormatado(), emp.getNome()};
                            tela.getTableModel().addRow(row);
                        }
                        break;
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ERRO_CONEXAO_BANCO);
            }

        });

        tela.getTblResultadoPesquisa().addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                super.mousePressed(e);

                // Verifica se foi um duplo clique e se alguma linha foi selecionada
                if (e.getClickCount() == 2
                        && tela.getTblResultadoPesquisa().getSelectedRowCount() > 0) {

                    try {
                        // Pega a linha selecionada
                        int rowSelected = tela.getTblResultadoPesquisa().getSelectedRow();

                        // Recupera o ID da empresa
                        Object id = tela.getTableModel().getValueAt(rowSelected, 0);

                        // Recupera os demais dados da empresa
                        empresaSelecionada = Empresa.buscarPorId((int) id);

                        // Mostra os dados da empresa na tela principal
                        jspCnpj.setText(empresaSelecionada.getCnpj());
                        lblNomeEmpresa.setText(empresaSelecionada.getNome());

                        // Fecha a tela
                        tela.setVisible(false);
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(TelaConvenios.this, ERRO_CONEXAO_BANCO);
                    }
                }
            }
        });

        tela.setVisible(true);
    }//GEN-LAST:event_btnPesquisaEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConvenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaConvenios dialog = new TelaConvenios(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisaEmpresa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbbCurso;
    private javax.swing.JComboBox<String> cbbSituacaoConvenio;
    private javax.swing.JFormattedTextField edtAssinatura;
    private javax.swing.JFormattedTextField edtVencimento;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JFormattedTextField jspCnpj;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblInicioAtual;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblSituacaoConvenio;
    private javax.swing.JPanel panEmpresa;
    // End of variables declaration//GEN-END:variables

    private void Limpar() {
        //limpa os componentes
        edtAssinatura.setText("");
        edtVencimento.setText("");
        jspCnpj.setText("");
        cbbCurso.setSelectedIndex(0);
        cbbSituacaoConvenio.setSelectedIndex(0);
        lblNomeEmpresa.setText("");
    }

    private void CursosComponente() {
        try {
            List<Curso> lista = Curso.buscarTodos("");
            // Limpa o componente
            cbbCurso.removeAllItems();
            cbbCurso.addItem(GERAL_SELECIONE_UM);
            lista.forEach(emp -> {
                cbbCurso.addItem(emp.getCurso());
            });
        } catch (SQLException ex) {
            Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }
    }

    private void SituacaoComponente() {
        try {
            List<ConvenioSituacao> lista = ConvenioSituacao.buscarTodos();
            // Limpa o componente
            cbbSituacaoConvenio.removeAllItems();
            cbbSituacaoConvenio.addItem(GERAL_SELECIONE_UM);
            lista.forEach(ConvenioSituacao -> {
                cbbSituacaoConvenio.addItem(ConvenioSituacao.getNome());
            });
        } catch (SQLException ex) {
            Logger.getLogger(TelaContrato.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }
    }
}
