/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui;

import static br.newtonpaiva.util.Mensagens.*;
import br.newtowpaiva.modelo.Convenio;
import br.newtowpaiva.modelo.ConvenioSituacao;
import br.newtowpaiva.modelo.Curso;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class TodosConvenios extends javax.swing.JDialog {

    /**
     * Creates new form TodosConvenios
     *
     * @param parent
     * @param modal
     */
    public TodosConvenios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
        * posiciona a tela no centro da tela
         */
        setLocationRelativeTo(parent);
        /*
        * Atualiza a tabela
         */
        atualizarTabela();

        SituacaoComponente();

        CursosComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        cbbSituacaoConvenio = new javax.swing.JComboBox<>();
        lblSituacaoConvenio = new javax.swing.JLabel();
        cbbCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();
        lblInicioAtual = new javax.swing.JLabel();
        edtAssinatura = new javax.swing.JFormattedTextField();
        lblDataEntrada = new javax.swing.JLabel();
        edtVencimento = new javax.swing.JFormattedTextField();
        jspCnpj = new javax.swing.JFormattedTextField();
        lblCnpj = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConvenios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Todos convênios");
        setResizable(false);

        panBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cbbSituacaoConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona um..." }));

        lblSituacaoConvenio.setText("Situação do convênio");

        cbbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona um..." }));

        lblCurso.setText("Curso");

        lblInicioAtual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblInicioAtual.setText("Data de assinatura");

        try {
            edtAssinatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDataEntrada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataEntrada.setText("Data de vencimento");

        try {
            edtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jspCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jspCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jspCnpjFocusLot(evt);
            }
        });

        lblCnpj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCnpj.setText("CNPJ");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBuscarLayout = new javax.swing.GroupLayout(panBuscar);
        panBuscar.setLayout(panBuscarLayout);
        panBuscarLayout.setHorizontalGroup(
            panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSituacaoConvenio)
                            .addComponent(cbbSituacaoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurso)
                            .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInicioAtual)
                            .addComponent(edtAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(193, 193, 193)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataEntrada)
                            .addComponent(edtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCnpj)
                            .addComponent(jspCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panBuscarLayout.setVerticalGroup(
            panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblSituacaoConvenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbSituacaoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(lblInicioAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBuscarLayout.createSequentialGroup()
                        .addComponent(lblDataEntrada)
                        .addGap(8, 8, 8)
                        .addComponent(edtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBuscarLayout.createSequentialGroup()
                        .addComponent(lblCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNovo))
                    .addGroup(panBuscarLayout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        tblConvenios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblConvenios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(panBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(imgLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(panBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        /*
        * Atualiza a tabela
         */
        atualizarTabela();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jspCnpjFocusLot(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jspCnpjFocusLot
        //Busca por empresa
    }//GEN-LAST:event_jspCnpjFocusLot

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        /*
        * Chama a tela de Contrato com o modal
         */
        TelaConvenios Tela = new TelaConvenios(null, true);
        /*
        * Tela de Contrato visivel
         */
        Tela.setVisible(true);

        atualizarTabela();

        JOptionPane.showMessageDialog(null, GERAL_GRADE_ATUALIZADA);
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosConvenios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TodosConvenios dialog = new TodosConvenios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cbbCurso;
    private javax.swing.JComboBox<String> cbbSituacaoConvenio;
    private javax.swing.JFormattedTextField edtAssinatura;
    private javax.swing.JFormattedTextField edtVencimento;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jspCnpj;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDataEntrada;
    private javax.swing.JLabel lblInicioAtual;
    private javax.swing.JLabel lblSituacaoConvenio;
    private javax.swing.JPanel panBuscar;
    private javax.swing.JTable tblConvenios;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {

        try {

            DefaultTableModel tableModel = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tableModel.addColumn(GERAL_ID);
            tableModel.addColumn("Empresa");
            tableModel.addColumn("Curso");
            tableModel.addColumn("Situação do covênio");
            tableModel.addColumn("Data de vencimento");
            tableModel.addColumn("Data de assinatura");
            tableModel.setRowCount(0);

            String dataAssinatura;

            if (edtAssinatura.getText().equals("  /  /    ")) {
                dataAssinatura = "";
            } else {
                dataAssinatura = edtAssinatura.getText();
            }

            String dataVencimento;

            if (edtVencimento.getText().equals("  /  /    ")) {
                dataVencimento = "";
            } else {
                dataVencimento = edtVencimento.getText();
            }

            String cnpj;

            if (jspCnpj.getText().equals("  .   .   /    -  ")) {
                cnpj = "";
            } else {
                cnpj = jspCnpj.getText();
            }

            String situacaoConvenio;

            if (cbbSituacaoConvenio.getSelectedIndex() == 0) {
                situacaoConvenio = "";
            } else {
                situacaoConvenio = cbbSituacaoConvenio.getSelectedItem().toString();
            }

            String curso;

            if (cbbCurso.getSelectedIndex() == 0) {
                curso = "";
            } else {
                curso = cbbCurso.getSelectedItem().toString();
            }

            List<Convenio> lista = Convenio.buscarTodos(dataAssinatura, dataVencimento, cnpj, situacaoConvenio, curso);

            lista.forEach(convenios -> {
                //Denomiar tempo para colorir as linhas
                if (convenios.getId() == 18) {
                    tblConvenios.setBackground(Color.CYAN);
                }
                SimpleDateFormat f = new SimpleDateFormat(GERAL_FORMATO_DATA);
                Object[] row = {convenios.getId(), convenios.getEmpresa().getNome(),
                    convenios.getCurso().getCurso(), convenios.getConvenioSituacao().getNome(),
                    f.format(convenios.getDataVencimento().getTime()),
                    f.format(convenios.getDataAssinatura().getTime())
                };
                tableModel.addRow(row);
            });
            tblConvenios.setModel(tableModel);
        } catch (SQLException ex) {
            Logger.getLogger(TodosConvenios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CursosComponente() {
        try {
            List<Curso> lista = Curso.buscarTodos("");
            // Limpa o componente
            cbbCurso.removeAllItems();
            cbbCurso.addItem(GERAL_SELECIONE_UM);
            lista.forEach(emp -> {
                cbbCurso.addItem(emp.getCurso());
            });

        } catch (SQLException ex) {
            Logger.getLogger(TelaContrato.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }
    }

    private void SituacaoComponente() {
        try {
            List<ConvenioSituacao> lista = ConvenioSituacao.buscarTodos();
            // Limpa o componente
            cbbSituacaoConvenio.removeAllItems();
            cbbSituacaoConvenio.addItem(GERAL_SELECIONE_UM);
            lista.forEach(ConvenioSituacao -> {
                cbbSituacaoConvenio.addItem(ConvenioSituacao.getNome());
            });

        } catch (SQLException ex) {
            Logger.getLogger(TelaContrato.class
                    .getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }
    }
}
