/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui;

import javax.swing.JFrame;

/**
 *
 * @author tarle
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnContrato = new javax.swing.JButton();
        btnAluno = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Contratos");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                autenticar(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        btnContrato.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1476690191_Document_Contract.png"))); // NOI18N
        btnContrato.setText("Registro de Contrato");
        btnContrato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContrato.setPreferredSize(new java.awt.Dimension(200, 200));
        btnContrato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnContrato);

        btnAluno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1476760762_Student-3.png"))); // NOI18N
        btnAluno.setText("Cadastro de Aluno");
        btnAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAluno.setPreferredSize(new java.awt.Dimension(200, 200));
        btnAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAluno);

        btnUsuario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1476690136_floppy.png"))); // NOI18N
        btnUsuario.setText("Cadastro de Usuario");
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setPreferredSize(new java.awt.Dimension(200, 200));
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnUsuario);

        btnEmpresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1476760778_company.png"))); // NOI18N
        btnEmpresa.setText("Cadastro de Empresa");
        btnEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpresa.setPreferredSize(new java.awt.Dimension(200, 200));
        btnEmpresa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnEmpresa);

        jButton5.setText("jButton5");
        jButton5.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(jButton5);

        jButton6.setText("jButton6");
        jButton6.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(jButton6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlunoActionPerformed

    private void autenticar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_autenticar
        // TODO add your handling code here:
        TelaLogin tela = new TelaLogin(this, true);
        tela.setVisible(true);
        
        if(!tela.isAutenticado()) {
            //setVisible(false);
            dispose();
        }
        
        tela.dispose();
        
    }//GEN-LAST:event_autenticar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnContrato;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnUsuario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
}
