/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.newtonpaiva.gc.ui;

import static br.newtonpaiva.util.Mensagens.*;
import br.newtowpaiva.modelo.Usuario;
import br.newtowpaiva.modelo.execoes.EmailInvalidoException;
import br.newtowpaiva.modelo.execoes.LoginIgualException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoConfirmacaoSenhaNuloException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoEmailExisteException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoEmailIdIgualException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoEmailNuloException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoLoginIdIgualException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoLoginNuloException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoNomeNuloException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoSenhaConfirmacaoSenhaNuloException;
import br.newtowpaiva.modelo.execoes.UsuarioInvalidoSenhaNuloException;
import br.newtowpaiva.modelo.execoes.UsuarioTamanhoEmailInvalidoException;
import br.newtowpaiva.modelo.execoes.UsuarioTamanhoLoginInvalidoException;
import br.newtowpaiva.modelo.execoes.UsuarioTamanhoNomeInvalidoException;
import br.newtowpaiva.modelo.execoes.UsuarioTamanhoSenhaInvalidoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class TelaUsuario extends javax.swing.JDialog {

    private Usuario usuarioEdicao;

    /**
     * Creates new form TelaUsuario
     * @param parent
     * @param modal
     */
    public TelaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*
        * posiciona a tela no centro da tela
         */
        setLocationRelativeTo(parent);
        /*
        * ao usuário clicar enter ele aciona o botão Salvar
         */
        getRootPane().setDefaultButton(btnSalvar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLogo = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        edtLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfSenha = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        edtSenha = new javax.swing.JPasswordField();
        edtConfSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        lblNome.setText("Nome");

        lblLogin.setText("Login");

        lblSenha.setText("Senha");

        lblConfSenha.setText("Confirmar senha");

        lblEmail.setText("Email");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(imgLogo)
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmail)
                    .addComponent(lblConfSenha)
                    .addComponent(lblSenha)
                    .addComponent(lblLogin)
                    .addComponent(edtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(lblNome)
                    .addComponent(edtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar))
                    .addComponent(edtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(edtSenha)
                    .addComponent(edtConfSenha))
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblConfSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        /*
        * Limpa os componentes
         */
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String Inserir = "N";
        //Se o usuario edição é nulo
        if (usuarioEdicao == null) {
            //Inicia uma nova classe
            usuarioEdicao = new Usuario();
            Inserir = "S";
        }
        //Seta o nome do curso para salvar (Inserir ou editar)
        usuarioEdicao.setEmail(edtEmail.getText());
        usuarioEdicao.setLogin(edtLogin.getText());
        usuarioEdicao.setNome(edtNome.getText());
        usuarioEdicao.setSenha(String.valueOf(edtSenha.getPassword()));
        usuarioEdicao.setConfSenha(String.valueOf(edtConfSenha.getPassword()));
        try {
            //Salvar
            usuarioEdicao.salvar();
            if (Inserir.equals("S")) {
                JOptionPane.showMessageDialog(null, USUARIO_INCLUIR_OK);
                /*
                * Limpa os componentes 
                 */
                limpar();
                usuarioEdicao = null;
            } else {
                JOptionPane.showMessageDialog(null, USUARIO_OK_ALTERAR);
            }
        } catch (UsuarioInvalidoNomeNuloException ex) {
            edtNome.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_NOME_NULO);
        } catch (UsuarioTamanhoNomeInvalidoException ex) {
            edtNome.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_NOME_MAXIMO);
        } catch (UsuarioInvalidoLoginNuloException ex) {
            edtLogin.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_NOME_NULO);
        } catch (UsuarioTamanhoLoginInvalidoException ex) {
            edtLogin.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_LOGIN_MAXIMO);
        } catch (LoginIgualException | UsuarioInvalidoLoginIdIgualException ex) {
            edtLogin.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_LOGIN_EXISTENTE);
        } catch (UsuarioInvalidoSenhaNuloException ex) {
            edtSenha.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_SENHA_NULO);
        } catch (UsuarioTamanhoSenhaInvalidoException ex) {
            edtSenha.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_SENHA_MAXIMO);
        } catch (UsuarioInvalidoConfirmacaoSenhaNuloException ex) {
            edtConfSenha.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_CONFIRMACAO_SENHA_NULO);
        } catch (UsuarioInvalidoSenhaConfirmacaoSenhaNuloException ex) {
            edtSenha.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_CONFIRMACAO_SENHA_DIFERENTE);
        } catch (UsuarioInvalidoEmailNuloException ex) {
            edtEmail.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_EMAIL_NULO);
        } catch (EmailInvalidoException ex) {
            edtEmail.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, GERAL_EMAIL_INVALIDO);
        } catch (UsuarioInvalidoEmailExisteException | UsuarioInvalidoEmailIdIgualException ex) {
            edtEmail.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_EMAIL_EXISTENTE);
        } catch (UsuarioTamanhoEmailInvalidoException ex) {
            edtEmail.requestFocus();
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, USUARIO_EMAIL_MAXIMO);
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ERRO_CONEXAO_BANCO);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    public void exibirDados(Usuario u) {
        //Iguala a classe que veio a variavel global
        usuarioEdicao = u;
        //seta os valores da classe aos campos
        edtEmail.setText(u.getEmail());
        edtLogin.setText(u.getLogin());
        edtNome.setText(u.getNome());
        edtSenha.setVisible(false);
        edtConfSenha.setVisible(false);
        lblSenha.setVisible(false);
        lblConfSenha.setVisible(false);
        //Desabilita o botão limpar
        btnLimpar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaUsuario dialog = new TelaUsuario(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPasswordField edtConfSenha;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblConfSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        /*
        * Limpa os componentes 
         */
        edtConfSenha.setText("");
        edtEmail.setText("");
        edtLogin.setText("");
        edtNome.setText("");
        edtSenha.setText("");
    }
}
